# numpy


In [10]:
import numpy as np

#### Инициализация массивовов, преобразовние типов данных

In [30]:
a1 = np.array([1,2,3,4])
print(a1)
print(type(a1))

a2 = np.array([1.2, -2, 3, 4])
print(a2)
print(a2.dtype) 

[1 2 3 4]
<class 'numpy.ndarray'>
[ 1.2 -2.   3.   4. ]
float64


In [31]:
# атрибуты
print(a1.shape)
print(a1.dtype) # массив однотипных данных


(4,)
int64


In [32]:
vau = np.array([1, 2, -5, 'hello'])
print(vau) # все сделал строками 

['1' '2' '-5' 'hello']


In [33]:
print(a2)
a2 = a2.astype(np.uint64)
print(a2)

[ 1.2 -2.   3.   4. ]
[1 0 3 4]


/var/folders/tw/0xxcpj311px323qzr54yqgkr0000gn/T/ipykernel_30670/1613037006.py:2: RuntimeWarning: invalid value encountered in cast
  a2 = a2.astype(np.uint64)


### Случайное распределение близкие к нормальное

In [35]:
a3 = np.random.randn(5)
a3

array([ 0.45850852, -1.22955413, -0.91121107, -0.41057628,  0.03693874])

In [38]:
np.mean(a3) # мат ожидание 

-0.41117884527850396

In [39]:
np.var(a3) # отклонение

0.37538723712572164

### Матрицы

In [41]:
arr2d = np.array([[1,2,3],[3,4,5],[5,6,7]])
print(arr2d)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [44]:
arr2d.shape

(3, 3)

In [43]:
np.random.randn(2,3)

array([[ 0.5877905 , -0.26718475, -1.49666262],
       [ 0.83433992, -1.12660246,  0.20354067]])

In [46]:
print(arr2d[0][1])
print(arr2d[0,1])

2
2


In [48]:
arr2d[1:,:2] = [[5, 6], [7, 8]] # срез заменяем на срез # c первой строки до второго столбца
print(arr2d)

[[1 2 3]
 [5 6 5]
 [7 8 7]]


In [49]:
arr2d[1:,:2] = [[5, 6]] #[[3]]
print(arr2d) # дублирует 

[[1 2 3]
 [5 6 5]
 [5 6 7]]


In [50]:
arr2d[1:,:2] = [[3]]
print(arr2d) # дублирует 

[[1 2 3]
 [3 3 5]
 [3 3 7]]


#### Случайные массивы

In [52]:
a4 = np.random.random(5)
a4

array([0.12111426, 0.89642585, 0.77186112, 0.01261718, 0.60989451])

In [59]:
a5 = np.empty(5) # псевдо случайные числа берет из буфера или печатает непойми что
a5

array([0.12111426, 0.89642585, 0.77186112, 0.01261718, 0.60989451])

#### Про копирование 

In [68]:
a6 = a5.copy()
print(a6)


[1.00000000e+02 8.96425850e-01 7.71861115e-01 1.26171819e-02
 6.09894506e-01]


In [69]:
np.tanh(a6)

array([1.        , 0.7145531 , 0.64801035, 0.01261651, 0.54405283])

#### Выборка данных

In [73]:
mask = (a5 >= 5) | (a5<0) #маска
print(mask)

[ True False False False False]


In [74]:
a5[mask] # сделали выборку 

array([100.])

In [75]:
print(a4, a5, sep='\n')

[0.12111426 0.89642585 0.77186112 0.01261718 0.60989451]
[1.00000000e+02 8.96425850e-01 7.71861115e-01 1.26171819e-02
 6.09894506e-01]


In [77]:
a5[a5>a6] # потому что a5 и a6 одинаковые 

array([], dtype=float64)

In [79]:
np.where(abs(a3)>abs(a4), a3, a4) # условие, если правда, если ложь

array([ 0.45850852, -1.22955413, -0.91121107, -0.41057628,  0.60989451])

In [80]:
np.maximum(a3, a4) 

array([0.45850852, 0.89642585, 0.77186112, 0.01261718, 0.60989451])

#### Сортировка данных 

In [85]:
a8 = np.random.randn(5)*10
print(a8)
a8.sort()
print(a8)

[ -4.2179801  -14.35822836  -8.81983099 -12.21680582   9.64784559]
[-14.35822836 -12.21680582  -8.81983099  -4.2179801    9.64784559]


In [107]:
arr3d = np.random.randn(3,3)*10
print(arr3d)

[[ -2.23322518   4.14989098  19.89384869]
 [-14.38125852  -4.30745663   0.94932522]
 [ -8.42897202  17.87090991   2.19620806]]


In [108]:
arr3d.sort(axis=0) # сортировка вдоль оси ноль по строкам
arr3d

array([[-14.38125852,  -4.30745663,   0.94932522],
       [ -8.42897202,   4.14989098,   2.19620806],
       [ -2.23322518,  17.87090991,  19.89384869]])

In [109]:
arr3d.sort(axis=1) # сортировка по столбцам
arr3d

array([[-14.38125852,  -4.30745663,   0.94932522],
       [ -8.42897202,   2.19620806,   4.14989098],
       [ -2.23322518,  17.87090991,  19.89384869]])

#### Некоторые функции

In [96]:
np.unique(arr2d)

array([-14.24529129,  -7.21546366,  -4.38102443,  -3.24684325,
        -1.02866418,  -0.50042943,   6.11490126,   7.59278508,
        16.9106125 ])

In [104]:
# раскидали на целые и дробыне 
r, d = np.modf(a3*10)
print(a3*10)
print(r)
print(d)

[  4.58508521 -12.29554134  -9.1121107   -4.10576281   0.36938738]
[ 0.58508521 -0.29554134 -0.1121107  -0.10576281  0.36938738]
[  4. -12.  -9.  -4.   0.]


In [118]:
print(a3)
np.sign(a3)

[ 0.45850852 -1.22955413 -0.91121107 -0.41057628  0.03693874]


array([ 1., -1., -1., -1.,  1.])

In [120]:
print(np.sign(arr2d))

[[-1.  1. -1.]
 [-1. -1. -1.]
 [-1.  1.  1.]]
